# Generated by Django 6.1.1 on 2026-09-18 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='referrals.referralnode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='referral_node', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendant_links', to='referrals.referralnode')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestor_links', to='referrals.referralnode')),
            ],
        ),
        migrations.AddConstraint(
            model_name='referralnode',
            constraint=models.UniqueConstraint(fields=('parent', 'position'), name='unique_referral_parent_position'),
        ),
        migrations.AddConstraint(
            model_name='referralnode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('parent__isnull', True), ('position__isnull', True)), models.Q(('parent__isnull', False), ('position__isnull', False)), _connector='OR'), name='valid_referral_parent_position'),
        ),
        migrations.AddIndex(
            model_name='referralclosure',
            index=models.Index(fields=['ancestor'], name='idx_closure_ancestor'),
        ),
        migrations.AddIndex(
            model_name='referralclosure',
            index=models.Index(fields=['descendant'], name='idx_closure_descendant'),
        ),
        migrations.AddConstraint(
            model_name='referralclosure',
            constraint=models.UniqueConstraint(fields=('ancestor', 'descendant'), name='unique_referral_ancestor_descendant'),
        ),
    ]
